### ISSUE TITLE
List social accounts

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/devfest-landing-2017#13]

**Comment by aalind0** [comment]
Add these links at the bottom of the page with proper icons matching the page's theme -
**Facebook** - [https://www.facebook.com/gdgvitvellore/](url)
**Twitter** - [https://twitter.com/gdgvit](url)
**Gplus** - [https://plus.google.com/+gdgvitvellore](url)
**Main website** - [http://gdgvitvellore.com/](url)

**Comment by ashwini0529** [comment]
We can add Github link as well @aalind0  😛

**Comment by aalind0** [comment]
I forgot that one, my bad (It's the most important one) - 
Github - [https://github.com/gdgvit](https://github.com/gdgvit)

**Comment by kodinglife** [comment]
Is it still open?

**Comment by aalind0** [comment]
Yeah, please go ahead. Also put a screenshot here when you are done.
