### ISSUE TITLE
Change radio to checkbox (IDEATHON, HACKATHON)

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/devfest-landing-2017#4]

**Comment by digaant333** [comment]
Hi , Please assign this to me

**Comment by ashwini0529** [comment]
Hey, unfortunately, Github doesn't allow to assign the issue to someone who's not a part of the organisation. You can grab this issue and submit a PR.! 😄

**Comment by digaant333** [comment]
And changing radio to checkbox means both can be checked together . Right ?

**Comment by ashwini0529** [comment]
Yeah correct. @digaant333

**Comment by technophilic** [comment]
fixed in PR #18
