### ISSUE TITLE
Contact us details

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/devfest-landing-2017#8]
there's no way they can contact us. add contact details.

**Comment by ashwini0529** [comment]
Email: gdgvitvellore@gmail.com
Location: VIT University, Vellore
Contact: +91-9414010878

**Comment by VijayGomathi** [comment]
I will add that

**Comment by ashwini0529** [comment]
Alright! 👍 
Please discuss the designs here before you send a PR. 😄

**Comment by VijayGomathi** [comment]
sorry @ashwini0529 I will not be doing this because you have used many frameworks that I am not aware of. I thought it as a simple task

**Comment by ashwini0529** [comment]
It's a simple task @VijayGomathi ! Just try reading the code once. 😄 
Still, if you find it tough, you can look after other issues in the repo. 😄
